remote_theme: minima
plugins:
- jekyll-remote-theme

# Setup
title:  "The Effects of Redlining on the Black Community of Portland"             
tagline:             
description:         
url:     http://eng470-s23.github.io          
baseurl:   /djwooley-demosite/            
